version: '3'

services:
  db:
    container_name: comics_db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
      - POSTGRES_DB=django
  django:
    container_name: comics_django
    build: .
    command: bash /opt/django/deploy/runserver.sh
    volumes:
      - .:/opt/django
      - ./deploy/certs:/etc/letsencrypt
      - ./deploy/nginx:/etc/nginx/sites-enabled
      - ./deploy/static:/var/www/static
      - ./deploy/media:/var/www/media
    ports:
      - "8000:8000"
      - "80:80"
      - "443:443"
    depends_on:
      - db
